### ISSUE TITLE
如何不使用代理和DDNS，局域网直连9000端口

### ISSUE THREAD

**Issue by yknext** [xm0625/XwareClient#1]
如何不使用代理和DDNS，局域网直连9000端口

**Comment by xm0625** [comment]
直连9000端口没有支持,后面可能(只是可能)考虑加上直连支持.现在只支持通过python架设的代理程序访问9000端口.不使用ddns,如果能知道ip也是可以直接连接的.
其实这个插件是为了替代迅雷远程(yuancheng.xunlei.com)的功能, 那么势必会有这样的场景:人在公司,操作家里的下载器添加下载任务,查看实时下载速度.而如果假设迅雷没有做限制,9000端口可以随意访问,那么直接暴露9000端口来远程连接,安全性是个问题.而加上这个python的小代理程序,就是为了发挥权限控制的作用,二来就是为了绕过9000端口对访问者ip的限制.
那如果是直连9000端口,如果你在你的笔记本上装一个插件,带笔记本出门了,插件随即就是失效了.然后你还得切成外网访问(代理+DDNS/公网ip).除非你配合一个连入家中的vpn,而vpn的架设,比跑一个python脚本难度要略大(毕竟连在路由器上安装python的教程都一搜一大把).
有一个改进方案是对于硬件条件不足的机器(连装python都装不了的路由器),采用C写一个功能一样的代理做成openwrt/luci插件.但是这个麻烦也略显麻烦.不同的CPU架构得提供不同的包,真的是...反人类.
所以目前,并没有改造代理的打算....唯一的想法是把这个浏览器插件的功能用一个html单页面把功能都实现,这样手机就可以直接操作了(iOS的AppStore审核真心累,直接断送了我做App的想法)....类似Aria2的单页面控制端

**Comment by yknext** [comment]
可以考虑用n2n或者自己搭建个后台
