### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by XKangs** [xm0625/XwareClient#2]
![qq 20171201205648](https://user-images.githubusercontent.com/17783163/33483719-248a8234-d6da-11e7-9686-61ec6a8d9e8d.png)

**Comment by xm0625** [comment]
能描述一下使用环境吗？

**Comment by xm0625** [comment]
可以使用ProcessOn画图

**Comment by XKangs** [comment]
Ubuntu 17.10 (GNU/Linux 4.9.66-040966-generic i686)
Python 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0] on linux2

**Comment by XKangs** [comment]
查了一下，好像是返回的内容没发完连接就断了的时候就会这样。都是英文没看懂

**Comment by xm0625** [comment]
这个应该不会导致server crash吧？这个只是打印异常信息而且，不用理会。
